conn_sock: Explicitly free a heap-allocated string
GCC does not complain about the variable here being unused, but clang
does:

../src/conn_sock.c:134:23: error: unused variable 'symlink_dir_path' [-Werror,-Wunused-variable]
        _cleanup_free_ char *symlink_dir_path =
                             ^
1 error generated.