Fix compilation with clang
This fixes the missing field initializers error when compiling with
clang:

```
src/conmon.c:119:7: error: missing field 'short_name' initializer
        {NULL}};
             ^
```

Signed-off-by: Sascha Grunert <sgrunert@suse.com>